### ISSUE TITLE
segfault during solve

### ISSUE THREAD

**Issue by wtholliday** [nzfeng/signed-heat-3d#1]
To reproduce:

1. bin/main ../data/knot.obj
2. select "on grid"
3. click Solve

![image](https://github.com/user-attachments/assets/9b540663-0dc4-4ebe-ae55-f4ed743ba7a6)

![image](https://github.com/user-attachments/assets/c9398e09-2d37-45e2-b897-65011ddb6d6e)

Did you mean to use `d` instead of `b` to compute a cell index? (`d` is unused)

**Comment by nzfeng** [comment]
Hey, good catch! Yup, `d` is supposed to be used instead of `b` on lines 89-91. Fixed in [358bba8](https://github.com/nzfeng/signed-heat-3d/commit/358bba80fc7ac90052e0ad8d8bdcc14327c48775)
